#!/bin/bash

# This file is meant to be run on a fresh installation of 
# raspbian to setup a wifi mapping sensor image from scratch.

echo "Copying env file into /home/pi/env..."
cp env /home/pi/env

echo "Copying sensor_logic file into /home/pi/sensor_logic..."
cp sensor_logic /home/pi/sensor_logic

echo "Copying source files..."
sudo cp sources.list.d/kismet.list /etc/apt/sources.list.d/kismet.list
sudo cp sources.list.d/raspi.list /etc/apt/sources.list.d/raspi.list
sudo cp sources.list.d/re4son.list /etc/apt/sources.list.d/re4son.list
sudo cp sources.list.d/zerotier.list /etc/apt/sources.list.d/zerotier.list

echo "Installing Nano, VIM, Parallel, Kismet, SQLite3, and UUIDgen..."
wget -O - https://www.kismetwireless.net/repos/kismet-release.gpg.key | sudo apt-key add -
sudo apt update
sudo apt install nano vim parallel -y
sudo apt install kismet sqlite3 uuid-runtime -y

echo "Installing gpsd"
sudo apt install gpsd gpsd-clients python-gps gpsbabel -y
sudo systemctl enable gpsd

echo "Making directories for kismet, gpspipe and zipped logs..."
sudo mkdir -p /home/pi/kismet
sudo mkdir -p /home/pi/gpspipe
sudo mkdir -p /home/pi/zipped

echo "Copying kismet files into /etc/kismet/..."
sudo mkdir -p /etc/kismet/
sudo cp kismet/* /etc/kismet/

echo "Installing ZeroTier..."
curl -s https://install.zerotier.com | sudo bash

echo "Installing sensor.service..."
sudo cp sensor.service /etc/systemd/system/sensor.service
sudo systemctl enable sensor.service

echo "Installing re4son kernel..."
wget -O - https://re4son-kernel.com/keys/http/archive-key.asc | sudo apt-key add -
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y \
  kalipi-kernel kalipi-bootloader kalipi-re4son-firmware \
  kalipi-kernel-headers libraspberrypi0 libraspberrypi-dev \
  libraspberrypi-doc libraspberrypi-bin

echo "Installation complete. Please reboot your system."
echo "See https://google.com for how to turn this into a compressed '.img' file for mass installation."
