#!/bin/bash

# Ensure we get our environment variables from this installation
source /home/pi/env

MYHOSTNAME=$(cat /etc/hostname)

echo "Checking Hostname: $MYHOSTNAME"
if [ "$MYHOSTNAME" = "raspberrypi" ]; then
  echo "Looks like we need a new hostname."
  NEW_UUID=$(uuidgen)
  echo "Changing hostname to $NEW_UUID..."

  echo "$NEW_UUID" > /etc/hostname
  echo "127.0.0.1 $NEW_UUID" >> /etc/hosts

  echo "Removing default image ZeroTier identity..."
  rm -rf /var/lib/zerotier-one/identity.*

  echo "Rebooting..."
  reboot
else
  echo "Joining Zero Tier Network..."
  sudo zerotier-cli join $ZEROTIER_NETWORK

  echo "Converting gpspipe output into KML and CSV formats..."
  sudo gpsbabel -i nmea -f /home/pi/gpspipe/output.nmea -o kml -F /home/pi/gpspipe/output.kml
  sudo gpsbabel -t -i nmea -f /home/pi/gpspipe/output.nmea -o unicsv -F /home/pi/gpspipe/output.csv

  echo "Zipping all data..."
  filename=$(date '+%Y-%m-%d-%s')
  sudo tar -zcvf "/home/pi/zipped/$filename-$HOSTNAME-kismet.tar.gz" /home/pi/kismet
  sudo tar -zcvf "/home/pi/zipped/$filename-$HOSTNAME-gpspipe.tar.gz" /home/pi/gpspipe

  echo "Removing original data..."
  sudo rm /home/pi/kismet/*
  sudo rm /home/pi/gpspipe/*

  echo "Attempting to upload..."
  echo "$SCP_USER@$SCP_SERVER:$SCP_DIRECTORY" | parallel -t --retries 5 --delay 30 sudo -u pi scp "/home/pi/zipped/$filename-$HOSTNAME-kismet.tar.gz" 
  echo "$SCP_USER@$SCP_SERVER:$SCP_DIRECTORY" | parallel -t --retries 5 --delay 30 sudo -u pi scp "/home/pi/zipped/$filename-$HOSTNAME-gpspipe.tar.gz" 

  echo "Upload script completed. Uploaded file: $filename-$HOSTNAME"
  
  echo "Entering Monitor Mode..."

  echo "Bringing wlan0 down..."
  sudo ifconfig wlan0 down

  echo "Creating mon0..."
  sudo iw phy phy0 interface add mon0 type monitor

  echo "Bringing mon0 up..."
  sudo ifconfig mon0 up

  echo "Waiting 10 seconds for mon0 to activate..."
  sleep 10

  echo "Starting Kismet service..."
  sudo service kismet start
  
  echo "Starting gpspipe in the background..."
  sudo gpspipe -r -o /home/pi/gpspipe/output.nmea

  echo "Scanning..."
fi
